# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8940251824878e89e46af4253f8384dc7fa06ba9b100444a1c1f44b10e8c651a7e1c25379aee1b40675e35d2df6d75b61653134593b71f4ee25f8b8763e8c98

test:
  secret_key_base: f0647e8e99a5b59ad73056db52c3b1a1689fc262b026eb93742b02898cf5c75e43fa13ecd67de3512e4f8a59b0bf272b6017d5c21de43765daae435c4fc743e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
